server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
  application:
    name: sub-security-demo

#  security:
#    user:
#      name: root
#      password: root
google:
  captcha:
    kaptcha:
      image:
        width: 150
        height: 50
      textproducer:
        char:
          string: "0123456789"
          length: 4